const actionTypes = {
  SET_NOTE: "SET_NOTE",
  ADD_NOTE: "ADD_NOTE",
  UPDATE_NOTE: "UPDATE_NOTE",
  DELETE_NOTE: "DELETE_NOTE",
  ATTACH_NOTE: "ATTACH_NOTE",
  UNATTACH_NOTE: "UNATTACH_NOTE",
  OPEN_MODAL: "OPEN_MODAL",
  ID_RANDOM: "ID_RAMDOM",
  CLEAR_NOTE: "CLEAR_NOT",
};
export default actionTypes;
